###
POST http://localhost:5000/api/v1/post/comment
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
    "postId": "608eaab03b48b1869d03926d",
    "comment": "This is another comment by me",
    "profilePicture": "",
    "userTo": "60903f191f9bedc7a3cfb727"
}

###
GET http://localhost:5000/api/v1/post/comments/608ea523c079ee706153bcc6/1
content-type: application/json
Accept: 'application/json'
withCredentials: true

###
GET http://localhost:5000/api/v1/post/commentsnames/608ea523c079ee706153bcc6
content-type: application/json
Accept: 'application/json'
withCredentials: true

###
GET http://localhost:5000/api/v1/post/single/comment/608ea523c079ee706153bcc6/6092b6f7a300252bcf9dce4f
content-type: application/json
Accept: 'application/json'
withCredentials: true
