###
GET http://localhost:5000/api/v1/notifications
content-type: application/json
Accept: 'application/json'
withCredentials: true

###
PUT http://localhost:5000/api/v1/notification/609ea91116974af44f99c4ec
content-type: application/json
Accept: 'application/json'
withCredentials: true

{}

###
DELETE http://localhost:5000/api/v1/notification/609ea91116974af44f99c4ec
content-type: application/json
Accept: 'application/json'
withCredentials: true

{}
