@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "username": "",
  "email": "",
  "password": ""
}

###
POST {{baseUrl}}/{{urlPath}}/signin
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "username": "",
  "password": ""
}

###
GET {{baseUrl}}/{{urlPath}}/currentuser
content-type: application/json
Accept: 'application/json'
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/signout
content-type: application/json
Accept: 'application/json'
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/forgot-password
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "email": ""
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/:token
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "password": "",
  "confirmPassword": ""
}
