@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/images/:userId
content-type: application/json
Accept: 'application/json'
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/images/profile
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "image": ""
}

###
POST {{baseUrl}}/{{urlPath}}/images/background
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "image": ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/images/:imageId
content-type: application/json
Accept: 'application/json'
withCredentials: true

{}

###
DELETE {{baseUrl}}/{{urlPath}}/images/background/:bgImageId
content-type: application/json
Accept: 'application/json'
withCredentials: true

{}
