#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint:check || (
  echo 'ESLint check failed. Run npm run lint:fix, add fix and try to commit again.'
  false;
)

npm run prettier:check || (
  echo 'Preetier check failed. Run npm run prettier:fix, add fix and try to commit again.'
  false;
)

echo '✅ ✅ ✅ 😀 😀 😀 Okay, everuthing looks good. 😀 😀 😀 ✅ ✅ ✅'
